"""fijar_tipos_json_libro_vivo

Revision ID: ba7cdd0b3a1c
Revises: 
Create Date: 2026-07-27 11:42:42.813188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7cdd0b3a1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('arboles_progreso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('estado_crecimiento', sa.String(length=50), nullable=True),
    sa.Column('energia_vital', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_arboles_progreso_id'), 'arboles_progreso', ['id'], unique=False)
    op.create_table('libros_vivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('titulo_libro', sa.String(), nullable=True),
    sa.Column('capitulo_actual', sa.Integer(), nullable=True),
    sa.Column('paginas_completadas', sa.Integer(), nullable=True),
    sa.Column('capitulos_narrativos', sa.JSON(), nullable=True),
    sa.Column('resumen_adn', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_libros_vivos_id'), 'libros_vivos', ['id'], unique=False)
    op.create_table('misiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('titulo_mision', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('recompensa_puntos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_misiones_id'), 'misiones', ['id'], unique=False)
    op.create_table('pasaportes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('nivel_actual', sa.Integer(), nullable=True),
    sa.Column('puntos_experiencia', sa.Integer(), nullable=True),
    sa.Column('insignias', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_pasaportes_id'), 'pasaportes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pasaportes_id'), table_name='pasaportes')
    op.drop_table('pasaportes')
    op.drop_index(op.f('ix_misiones_id'), table_name='misiones')
    op.drop_table('misiones')
    op.drop_index(op.f('ix_libros_vivos_id'), table_name='libros_vivos')
    op.drop_table('libros_vivos')
    op.drop_index(op.f('ix_arboles_progreso_id'), table_name='arboles_progreso')
    op.drop_table('arboles_progreso')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
